### ISSUE TITLE
Share video doesn't work on Viber.

### ISSUE THREAD

**Issue by AndreNuvi** [commonsguy/cwac-provider#33] opened 2017-04-26 19:17 UTC
I only want to mention that share video from asset folder doesn't work on Viber.

**Comment by commonsguy** [comment] 2017-04-26 23:04
I am not going to test every possible combination of app and content, as there are too many apps. Most likely, either Viber does not handle any `content`, thinks that `content` must mean `MediaStore` and does stupid stuff, or needs a seekable stream (which I cannot produce directly from an asset).

If you try `FileProvider`, or `StreamProvider` with a regular file, and Viber now works, that suggests that the problem is with seekable streams.

Beyond that, look for LogCat stack traces coming from Viber when you try sharing the asset, and post it here. Without that, there is nothing that I can do.

**Comment by commonsguy** [comment] 2017-05-12 16:38
Closing, as I lack sufficient information to proceed.

**Closed by commonsguy** 2017-05-12 16:38 UTC
